### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by alanscarpa** [LogoGrab/logograb-sdk-ios#1]
Downloaded the sample app and tried to run on Xcode 7

Received this error:

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_LogoGrab", referenced from:
      objc-class-ref in LogoGrabSDK(LogoGrabApp.o)
     (maybe you meant: _OBJC_CLASS_$_LogoGrabApp, _OBJC_CLASS_$_LogoGrabSDK )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by alexprest** [comment]
Hi,
the LogoGrab SDK supports only device architecture.

However, there's a workaround if you want to have the LogoGrabSDK included in your project and still be able to debug in the simulator. Simply add the following code in your app delegate.m:

#if TARGET_IPHONE_SIMULATOR
@implementation LogoGrab : NSObject @end
#endif 

This will create the necessary symbol for the linker to return successfully. Clearly the logograb functionality won't be available in the simulator.

If you want to try out this solution quickly you can use the SampleApp included in the SDK and add the snippet above to AppDelegate.m You'll notice that you'll be able to run the sample app in the simulator.
